name: diploma
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - pip

  - python-dotenv
  - pydantic
  - tabulate
  - matplotlib
  - pandas
  - seaborn
  - pysam

  - flake8
  - yapf

  - bbmap=39.26
  - bwa
  - samtools
  - bcftools
  - htslib
  - tabix
  - varscan
  - qualimap
  - vcftools
  - glimpse-bio

  - pip:
      - .
